// Tests for bundleFrameworkDir + writeVersionFile.
// implements [FR-DIST.BUNDLE](https://github.com/korchasa/flowai/blob/main/documents/requirements.md#fr-dist.bundle-bundled-source)
import { assertEquals, assertStringIncludes } from "@std/assert";
import { join } from "@std/path";
import {
  bundleFrameworkDir,
  writeVersionFile,
} from "./bundle-framework-lib.ts";

async function makeFixture(): Promise<string> {
  const dir = await Deno.makeTempDir({ prefix: "flowai-bundle-fix-" });
  await Deno.mkdir(join(dir, "core", "skills", "x"), { recursive: true });
  await Deno.mkdir(join(dir, "core", "skills", "x", "acceptance-tests", "s"), {
    recursive: true,
  });
  await Deno.writeTextFile(join(dir, "core", "pack.yaml"), "name: core\n");
  await Deno.writeTextFile(
    join(dir, "core", "skills", "x", "SKILL.md"),
    "# X\n",
  );
  await Deno.writeTextFile(
    join(dir, "core", "skills", "x", "helper.ts"),
    "export const A = 1;\n",
  );
  await Deno.writeTextFile(
    join(dir, "core", "skills", "x", "helper_test.ts"),
    "// excluded\n",
  );
  await Deno.writeTextFile(
    join(dir, "core", "skills", "x", "acceptance-tests", "s", "mod.ts"),
    "// excluded\n",
  );
  return dir;
}

Deno.test("bundleFrameworkDir: includes prod files, excludes tests and acceptance-tests", async () => {
  const src = await makeFixture();
  const out = await Deno.makeTempFile({ suffix: ".json" });
  try {
    const count = await bundleFrameworkDir(src, out);
    assertEquals(count, 3);
    const parsed = JSON.parse(await Deno.readTextFile(out)) as Record<
      string,
      string
    >;
    const keys = Object.keys(parsed).sort();
    assertEquals(keys, [
      "framework/core/pack.yaml",
      "framework/core/skills/x/SKILL.md",
      "framework/core/skills/x/helper.ts",
    ]);
    assertEquals(parsed["framework/core/pack.yaml"], "name: core\n");
  } finally {
    await Deno.remove(src, { recursive: true });
    await Deno.remove(out);
  }
});

Deno.test("bundleFrameworkDir: byte-deterministic across two runs (FR-DIST.BUNDLE.PIN)", async () => {
  const src = await makeFixture();
  const out1 = await Deno.makeTempFile({ suffix: ".json" });
  const out2 = await Deno.makeTempFile({ suffix: ".json" });
  try {
    await bundleFrameworkDir(src, out1);
    await bundleFrameworkDir(src, out2);
    const a = await Deno.readFile(out1);
    const b = await Deno.readFile(out2);
    assertEquals(a, b, "two consecutive bundles must be byte-identical");
  } finally {
    await Deno.remove(src, { recursive: true });
    await Deno.remove(out1);
    await Deno.remove(out2);
  }
});

Deno.test("bundleFrameworkDir: output is sorted alphabetically by key", async () => {
  const src = await Deno.makeTempDir({ prefix: "flowai-bundle-sort-" });
  const out = await Deno.makeTempFile({ suffix: ".json" });
  try {
    await Deno.writeTextFile(join(src, "z.md"), "z\n");
    await Deno.writeTextFile(join(src, "a.md"), "a\n");
    await Deno.writeTextFile(join(src, "m.md"), "m\n");
    await bundleFrameworkDir(src, out);
    const json = await Deno.readTextFile(out);
    const aIdx = json.indexOf('"framework/a.md"');
    const mIdx = json.indexOf('"framework/m.md"');
    const zIdx = json.indexOf('"framework/z.md"');
    assertEquals(aIdx < mIdx && mIdx < zIdx, true, "keys must be sorted");
  } finally {
    await Deno.remove(src, { recursive: true });
    await Deno.remove(out);
  }
});

Deno.test("writeVersionFile: emits expected VERSION constant", async () => {
  const out = await Deno.makeTempFile({ suffix: ".ts" });
  try {
    await writeVersionFile("1.2.3", out);
    const body = await Deno.readTextFile(out);
    assertStringIncludes(body, 'export const VERSION = "1.2.3";');
    assertStringIncludes(
      body,
      "// Generated by scripts/bundle-framework.ts",
    );
  } finally {
    await Deno.remove(out);
  }
});
