// [FR-DIST.DETECT](https://github.com/korchasa/flowai/blob/main/documents/requirements.md#fr-dist.detect-ide-auto-detection) — IDE type definitions
// [FR-PACKS.CONFIG](https://github.com/korchasa/flowai/blob/main/documents/requirements.md#fr-packs.config-config-v1.1) — FlowConfig with packs field
// [FR-HOOK-RESOURCES.FORMAT](https://github.com/korchasa/flowai/blob/main/documents/requirements.md#fr-hook-resources.format-hook-format) — HookDefinition type
/** IDE definition */
export interface IDE {
  name: string;
  configDir: string;
}

/** Pack definition from pack.yaml */
export interface PackDefinition {
  name: string;
  version: string;
  description: string;
  /** skill-name → list of project-relative artifact paths generated by that skill */
  scaffolds?: Record<string, string[]>;
  /** template-filename → project-relative artifact path (pack-level asset mapping) */
  assets?: Record<string, string>;
}

/** .flowai.yaml config structure */
export interface FlowConfig {
  version: string;
  ides: string[];
  /** Pack names to install. undefined = legacy (all resources). [] = core only. */
  packs?: string[];
  skills: {
    include: string[];
    exclude: string[];
  };
  agents: {
    include: string[];
    exclude: string[];
  };
  commands: {
    include: string[];
    exclude: string[];
  };
  /** Cross-IDE user resource propagation (default: false) */
  userSync?: boolean;
  /** Framework source override: git branch/tag or local path */
  source?: SourceConfig;
  /** Model tier overrides per IDE: { claude: { smart: "opus" }, cursor: { smart: "slow" } } */
  models?: Record<string, Record<string, string>>;
  /** FR-DIST.CODEX-HOOKS — opt-in experimental feature flags. Default: all false. */
  experimental?: {
    /** Enable OpenAI Codex hook installation (experimental; gated on Codex's own `codex_hooks` feature flag). */
    codexHooks?: boolean;
  };
}

/** Downloaded file in memory */
export interface UpstreamFile {
  path: string;
  content: string;
}

/** Plan item action */
export type PlanAction = "create" | "update" | "ok" | "conflict" | "delete";

/** Hook definition from hook.yaml */
export interface HookDefinition {
  /** IDE event name (e.g., PostToolUse, PreToolUse) — Claude Code naming as canonical */
  event: string;
  /** Regex pattern to match tool/file names (optional) */
  matcher?: string;
  /** Human-readable description */
  description: string;
  /** Timeout in seconds. Default: 30 (PostToolUse), 600 (PreToolUse) */
  timeout?: number;
}

/** Plan item type */
export type PlanItemType =
  | "skill"
  | "agent"
  | "command"
  | "hook"
  | "script"
  | "asset";

/** Plan item for sync */
export interface PlanItem {
  type: PlanItemType;
  name: string;
  action: PlanAction;
  sourcePath: string;
  targetPath: string;
  content: string;
  /** mtime of the source file (hint for conflict prompt) */
  sourceMtime?: Date | null;
  /** mtime of the target file (hint for conflict prompt) */
  targetMtime?: Date | null;
}

/** Per-resource action breakdown for sync output */
export interface ResourceAction {
  name: string;
  action: "create" | "update" | "delete" | "ok";
  /** Scaffolded artifact paths (only for skills with scaffolds) */
  scaffolds: string[];
  /** True when write for this resource failed (renderer moves to ERRORS block
   * and subtracts from CREATED/UPDATED count shown as `written/planned`). */
  failed?: boolean;
}

/** Known IDE definitions */
export const KNOWN_IDES: Record<string, IDE> = {
  cursor: { name: "cursor", configDir: ".cursor" },
  claude: { name: "claude", configDir: ".claude" },
  opencode: { name: "opencode", configDir: ".opencode" },
  // [FR-DIST.DETECT](https://github.com/korchasa/flowai/blob/main/documents/requirements.md#fr-dist.detect-ide-auto-detection) — OpenAI Codex CLI. Skills land in `.codex/skills/`, which
  // Codex discovers natively (verified 2026-04-11 against codex-cli 0.118.0).
  codex: { name: "codex", configDir: ".codex" },
};

/** Default git URL for source.ref (official flowai repo) */
export const DEFAULT_GIT_URL = "https://github.com/korchasa/flowai.git";

/** Source configuration for .flowai.yaml */
export interface SourceConfig {
  /** Git repo URL (default: DEFAULT_GIT_URL) */
  git?: string;
  /** Branch or tag name */
  ref?: string;
  /** Local framework/ directory path */
  path?: string;
}

/** Default config values */
export const DEFAULT_VERSION = "1.0";

/** Config version with packs support */
export const PACKS_VERSION = "1.1";
